sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

matrix:
  include:
    # linux
    - os: linux   # abi 47
      env: NODE_VERSION="5.1.1" TARGET_ARCH="x64" CXX=g++-4.9
    - os: linux   # abi 48
      env: NODE_VERSION="6" TARGET_ARCH="x64" CXX=g++-4.9
    - os: linux   # abi 49
      env: NODE_VERSION="6" ELECTRON="1.3.6" TARGET_ARCH="x64" CXX=g++-4.9
    # os x x64
    - os: osx
      env: NODE_VERSION="5.1.1" TARGET_ARCH="x64" CXX="clang"
    - os: osx
      env: NODE_VERSION="6" TARGET_ARCH="x64" CXX="clang"
    - os: osx
      env: NODE_VERSION="6" ELECTRON="1.3.6" TARGET_ARCH="x64" CXX="clang"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 "https://github.com/creationix/nvm.git" ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - export PATH="$(pwd)/node_modules/.bin/:$PATH"

install:
  - if [[ -n "$ELECTRON" ]]; then
      export npm_config_target=$ELECTRON;
      export npm_config_disturl=https://atom.io/download/atom-shell;
      export npm_config_runtime=electron;
      export npm_config_build_from_source=true;
    fi
  - npm install

script:
  - if [[ -z "$ELECTRON" ]]; then
      npm test;
    fi
  - node-pre-gyp package testpackage

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/

before_deploy:
  - export RELEASE_NODE_FILE=$(find build/stage -name '*.tar.gz')
  - echo "Deploying $RELEASE_NODE_FILE to GitHub"

deploy:
  provider: releases
  api_key:
    secure: MdXMdAFzm2MUsDRRhGBiu2lautFO44n9F0htMwDzYNHNLCKdm3sSAIFjfLOVnq8MrBDR15r/5Ak2y8CNHHx8ty0f8hKFiHLtU3e/SIh7cX7JWzk2VA30vKaivuHYscX6LgE3RPjGSG5hm2eWP4bO2+yCVCFAC/fpmyOP8SaLOld9nDz3cLZ1I17fwXDHEcs/or1DGsTl9gk/rNg/D/qPlPDs5gzpick3omtSm6LZVdDdrAYftRUn3/FGLheO8Y7OrmtvG14Xp1MZnxOklIicFgZcFxKq7yCBhjfOq2ey9o9+uIBQyBEQFVArfwc0Fe5VFFcGE4f0BYh0qzevl61/hH72RQnkOdCs+wCOaDuUqYQtxGXmx4AqTGD5l9eNomJxRvzp/WwJUBoP8Fqg7vdJnq0GG9Es/PvB5NUjLYj5OcgXGSAHwmw3bGHveuXkY4dYAnctK7fgur4NS4OUuB78AIqcrViLZs86l0/hW70MbpLQuuCAz3BlN5Q256FIVox19NdfREZNnQxlk/1eWd+rWBFw+/ulBDYPFGH5osyHn5V7rTPKEqXXdygdk5dSvQKWVaJE+qQkpLyFGcqoKAP3F4bSXywJVA4pkIDyq7oD4ru92a/ZDf5F96DEtadWxqO5aVhVhzyKrPlMWgTuFxSOgZZVjgremjbqH/uGZYH6bk0=
  file: "$RELEASE_NODE_FILE"
  skip_cleanup: true
  on:
    repo: rightparen/pty.js-prebuilt
    tags: true
